version: '2'
services:
    boulder:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            FAKE_DNS: 172.17.0.1
            PKCS11_PROXY_SOCKET: tcp://boulder-hsm:5657
            BOULDER_CONFIG_DIR: test/config
        volumes:
          - .:/go/src/github.com/letsencrypt/boulder
          - /tmp:/tmp
        network_mode: bridge
        extra_hosts:
          - le.wtf:127.0.0.1
          - boulder:127.0.0.1
        ports:
          - 4000:4000 # ACME
          - 4002:4002 # OCSP
          - 4003:4003 # OCSP
          - 4430:4430 # ACME via HTTPS
          - 4500:4500 # ct-test-srv
          - 6000:6000 # gsb-test-srv
          - 8000:8000 # debug ports
          - 8001:8001
          - 8002:8002
          - 8003:8003
          - 8004:8004
          - 8005:8005
          - 8006:8006
          - 8008:8008
          - 8009:8009
          - 8010:8010
          - 8055:8055 # dns-test-srv updates
          - 9380:9380 # mail-test-srv
          - 9381:9381 # mail-test-srv
        links:
          - bhsm:boulder-hsm
          - bmysql:boulder-mysql
    bhsm:
        # To minimize the fetching of various layers this should match
        # the FROM image and tag in boulder/Dockerfile
        image: letsencrypt/boulder-tools:2017-05-25
        environment:
            PKCS11_DAEMON_SOCKET: tcp://0.0.0.0:5657
        command: /usr/local/bin/pkcs11-daemon /usr/lib/softhsm/libsofthsm.so
        expose:
          - 5657
        network_mode: bridge
    bmysql:
        image: mariadb:10.1
        network_mode: bridge
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: mysqld --bind-address=0.0.0.0
        logging:
            driver: none
    prom:
        image: prom/prometheus
        network_mode: bridge
        ports:
          - 9090:9090
        volumes:
          - $PWD/test/prometheus/:/promconf/
        command: -config.file /promconf/prometheus.yml
        links:
          - boulder
